#!/usr/bin/env sh

# https://stackoverflow.com/questions/3284292/can-a-git-hook-automatically-add-files-to-the-commit
if [ -e .commit ]
    then
    rm .commit
    bun run socialMedia:auto
    git add .
    git commit --amend -C HEAD --no-verify
fi
exit
