name: Quality gate
on: push
jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm run lint
      - name: CSS Linting Summary
        if: success()
        run: echo "✅ CSS property ordering and unused CSS checks completed as part of lint step"

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci || npm install
      - run: npm run test
